### ISSUE TITLE
invite to convo

### ISSUE THREAD

**Issue by dmitryame** [echowaves/echowaves.socialgroupchat#1]
Anyone should be able to invite anyone to a convo.
Comma delimited list of either emails or EW usernames

**Comment by dmitryame** [comment]
i was really thinking about just adding a user to a convo, well, this might work, though people should really go through the acceptance process, otherwise someone might be able to script adding new users and spam everyone this way

**Comment by crossblaim** [comment]
I have the idea of making this ultra simple and no intrusive, no acceptance process.

so an user just adds the user to the convo, but this not mean that the "invited user" is automatically subscribed (solves the SPAM issue), BUT from this point the user can access the convo like if the convo is public, the "invited user" then can subscribe to the convo if he wants

**Comment by dmitryame** [comment]
hmm, interesting,
where these private convos would appear for a user after he's been added?

How about public convos? The users should be able to add or invite the other users to public convos as well (to let people know about something interesting is going on).

What if we call it share instead of invite? Shared convos? We will need to have a list of shared convos exposed somewhere, maybe...

**Comment by crossblaim** [comment]
maybe we can show the pending subscriptions on the subscriptions page or show them in the convos list (in red) and make them searchable for the "invited" users

about inviting to public convos, this is not an important or interesting feature for me right now, if you want to invite one user to one public convo, or many users, just send them an email with the url or the name of the convo

**Comment by crossblaim** [comment]
share may work, but is just terminology, not sure about the list of shared convos, too complicated and innecessary

**Comment by dmitryame** [comment]
yeah, let's keep it simple

**Comment by dmitryame** [comment]
well, first of all, we should reimplement (simplify) convos list. 
There should be only 1!!!!! (one) convo list (instead of pubic, private, subcriptions, etc...)
There should be only 1 convo list, and it should show all the convos user has currently access to, and there should be indicators (or labels, what ever) next to each convo (public, private, subscribed, perhaps invited etc...).
Then the user on the same page should be easily able to filter and sort by type -- your've got the idea.
