### ISSUE TITLE
refactor the subscriber model 

### ISSUE THREAD

**Issue by dmitryame** [echowaves/echowaves.socialgroupchat#7]
To gain benefits of mongo, we really should be doing something like this, instead of modeling relational db

http://groups.google.com/group/mongoid/browse_thread/thread/f14ae338fef311d3?fwc=1&pli=1

**Comment by crossblaim** [comment]
do you mean the "subscription" model I guess

**Comment by crossblaim** [comment]
I don't understand, the code in the link you posted is still "relational", the users are not embeded at all, just the ids of the users are stored within the model in an array, and that means joins

**Comment by crossblaim** [comment]
what are the benefits of this?

**Comment by dmitryame** [comment]
yes, just the ids, still better then the join table that has ids, like subscription

**Comment by crossblaim** [comment]
will be easy or more efficient to query for all the users subscribed to a convo?

**Comment by dmitryame** [comment]
well, i'm just brainstorming, thinking aloud.
Perhaps there is not going to be a significant benefit.
I will delete this issue for now.

**Comment by dmitryame** [comment]
there does not seem a way to delete an issue in github, just closing it instead
